apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchants-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efood
      service: merchants
  template:
    metadata:
      labels:
        app: efood
        service: merchants
        sidecar.istio.io/inject: "true"
        version: "1"
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
      - name: merchants
        image: ghcr.io/wofood/efood_merchants
        # resources:
        #   requests:
        #     memory: "4G"
        #     cpu: "1000m"
        #   limits:
        #     memory: "8G"
        #     cpu: "2000m"
        ports:
          - name: merchants
            protocol: TCP
            containerPort: 3000
        envFrom:
          - configMapRef:
              name: efood-config
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
