apiVersion: v1
kind: Service
metadata:
  name: merchants-svc
  labels:
    app: efood
    service: merchants
spec:
  selector:
    app: efood
    service: merchants
  ports:
    - name: http-port
      port: 3000
