# name: Continuous Integration
# on: push
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - name: Install
#         run: npm install
#       - name: Run ESLint
#         run: npm run lint

name: Deploy Dev
on:
  push:
    branches:
      - "development"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install skaffold
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kubectl: '1.17.1'
          skaffold: '1.20.0'

      - name: Authenticate with Github Container Registry
        run: echo $GHCR_PASSWORD | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}

      - name: Deploy
        run: |
          echo "$KUBECONFIG" | base64 -d > /tmp/kubeconfig
          export KUBECONFIG=/tmp/kubeconfig
          skaffold run
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_DEV }}
